### ISSUE TITLE
Help Compiling Tailwind CSS

### ISSUE THREAD

**Issue by GrantNagel** [kylebutts/tailwindr#3]
Hi there,

I'm having trouble using your package to compile some tailwind.css in my rmarkdown file.

I'm trying to render this specific progress tracking component here

```r
<div class="relative pt-1">
  <div class="flex mb-2 items-center justify-between">
    <div>
      <span class="text-xs font-semibold inline-block py-1 px-2 uppercase rounded-full text-pink-600 bg-pink-200">
        Task in progress
      </span>
    </div>
    <div class="text-right">
      <span class="text-xs font-semibold inline-block text-pink-600">
        30%
      </span>
    </div>
  </div>
  <div class="overflow-hidden h-2 mb-4 text-xs flex rounded bg-pink-200">
    <div style="width:30%" class="shadow-none flex flex-col text-center whitespace-nowrap text-white justify-center bg-pink-500"></div>
  </div>
</div>
```

This is my YAML header. I need my style sheet to be inline in the resulting HTML. How would I structure it so it compiles the previous section of tailwind related HTML?

```yaml
---
title: "`r title`"
author: "`r author`"
date: "Date: `r Sys.Date()`"
output:
  html_document:
    pandoc_args: [
      "--css", "styles.css",
      "--self-contained"
    ]
---
```

I have tried this without success:

```yaml
output:
  tailwindr::tailwind:
    self_contained: true
    slim_css: TRUE
    css: ["styles.css"]
```

Any help would be greatly appreciated. Thanks
